### ISSUE TITLE
Session in readme

### ISSUE THREAD

**Issue by Tuhaj** [KatarzynaT-B/jump_in#10]
I just tried to use the gem without even looking at the dummy app, just following the readme and a first problem I had was `NameError: undefined local variable or method session for main:Object`
What is a session? How is it related to the `User`? Answers to these questions could be helpful. :-)

**Comment by KatarzynaT-B** [comment]
Can you be more specific? How did you use gem's methods and were?
Readme was thought rather as general description of gem's possibilities and main features, once we establish api, we will add wiki pages.

**Comment by Tuhaj** [comment]
This is not a bug. What I mean is that I couldn't easly figure out what is a session object and how to use it. I think it could be explained on examples in readme. But probably you have it already in your plans...
