### ISSUE TITLE
Use `Base64.urlsafe_encode64` when encoding tokens

### ISSUE THREAD

**Issue by jumski** [KatarzynaT-B/jump_in#14]
The unsafe version uses newlines, which can cause problems here and there.
I was using `Tokenizer.generate_token` for a custom auth token for [jumski/emberjs-blog](https://github.com/jumski/emberjs-blog), which ended with custom implementation, because browser allows only ascii-chars in headers.

**Comment by KatarzynaT-B** [comment]
Yeah, we also noticed that. We changed token generation so that it used urlsafe
